// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type ApiError = {
    code: string;
    message: string;
    details?: unknown;
};

export type ErrorEnvelope = {
    error: ApiError;
};

export type Health = {
    service: string;
    status: string;
    utc: string;
};

export type FeatureFlags = {
    discordOAuth: boolean;
    bootstrapAdminLogin: boolean;
    discordPublishing: boolean;
    discordDirectMessages: boolean;
    discordReminders: boolean;
};

export type Team = {
    teamId: string;
    name: string;
    isMainRoster: boolean;
    defaultLootMode: 'LOOT_COUNCIL' | 'NONE';
};

export type PlayerProfile = {
    userId: string;
    discordUserId?: string | null;
    discordUsername?: string | null;
    displayName: string;
    avatarHash?: string | null;
    isOfficer: boolean;
    teamIds: Array<string>;
    timeZone: string;
    authenticationProviders: Array<'DISCORD' | 'BOOTSTRAP'>;
    createdAt: string;
    updatedAt: string;
};

export type CharacterProfile = {
    characterId: string;
    userId: string;
    discordUserId?: string | null;
    name: string;
    realm: string;
    region: string;
    characterClass: string;
    primarySpec: string;
    eligibleRoles: Array<'TANK' | 'HEALER' | 'DPS'>;
    teamIds: Array<string>;
    isMain: boolean;
    verificationStatus: 'PENDING' | 'VERIFIED' | 'REJECTED';
    verificationMethod: string;
    verifiedByUserId?: string | null;
    verifiedAt?: string | null;
    createdAt: string;
    updatedAt: string;
};

export type BisItem = {
    itemId: number;
    itemName: string;
    slot: string;
    priority: number;
    source?: string | null;
    note?: string | null;
};

export type BisList = {
    characterId: string;
    version: number;
    phaseOrTier?: string | null;
    items: Array<BisItem>;
    updatedAt: string;
};

export type Raid = {
    raidId: string;
    teamId: string;
    title: string;
    instanceName: string;
    startsAt: string;
    endsAt?: string | null;
    status: 'DRAFT' | 'PUBLISHED' | 'CANCELLED' | 'COMPLETED';
    lootMode: string;
    discordMessageId?: string | null;
    publishVersion: number;
    version: number;
    createdByUserId: string;
    createdAt: string;
    updatedAt: string;
};

export type Signup = {
    raidId: string;
    userId: string;
    discordUserId?: string | null;
    characterId: string;
    status: 'ACCEPTED' | 'TENTATIVE' | 'DECLINED';
    note?: string | null;
    updatedAt: string;
};

export type RosterSlot = {
    characterId: string;
    role: string;
    group: number;
    position: number;
    note?: string | null;
};

export type RosterDocument = {
    raidId: string;
    version: number;
    roster: Array<RosterSlot>;
    bench: Array<RosterSlot>;
    updatedAt: string;
    updatedByUserId: string;
};

export type EncounterAssignment = {
    raidId: string;
    bossKey: string;
    bossName: string;
    version: number;
    generalNotes: string;
    tankTargetsByCharacterId: {
        [key: string]: string;
    };
    healGroupsByCharacterId: {
        [key: string]: string;
    };
    interruptOrderCharacterIds: Array<string>;
    positionNotesByCharacterId: {
        [key: string]: string;
    };
    personalNotesByCharacterId: {
        [key: string]: string;
    };
    updatedAt: string;
    updatedByUserId: string;
};

export type EncounterTemplate = {
    templateId: string;
    name: string;
    instanceName: string;
    bossKey: string;
    bossName: string;
    generalNotes: string;
    tankTargetLabels: Array<string>;
    healGroupLabels: Array<string>;
    interruptLabels: Array<string>;
    updatedAt: string;
};

export type LootAward = {
    awardId: string;
    raidId: string;
    teamId: string;
    characterId: string;
    userId: string;
    discordUserId?: string | null;
    itemId: number;
    itemName: string;
    itemLevel?: number | null;
    slot?: string | null;
    decisionType: string;
    priority?: string | null;
    note?: string | null;
    lootSystem: string;
    awardedByUserId: string;
    awardedAt: string;
    status: 'ACTIVE' | 'VOIDED';
    voidReason?: string | null;
    voidedByUserId?: string | null;
    voidedAt?: string | null;
    bisStatusAtAward?: string | null;
    bisPriorityAtAward?: number | null;
};

export type ExchangeLoginCodeRequest = {
    code: string;
};

export type ExchangeBootstrapAdminRequest = {
    token: string;
};

export type UpdatePlayerRequest = {
    displayName?: string;
    teamIds?: Array<string>;
    timeZone?: string;
};

export type CharacterRequest = {
    name: string;
    realm: string;
    region: string;
    characterClass: string;
    primarySpec: string;
    eligibleRoles: Array<string>;
    teamIds: Array<string>;
    isMain: boolean;
};

export type VerifyCharacterRequest = {
    approved?: boolean;
    note?: string | null;
};

export type SaveBisListRequest = {
    expectedVersion?: number | null;
    phaseOrTier?: string | null;
    items: Array<BisItem>;
};

export type CreateRaidRequest = {
    teamId: string;
    title: string;
    instanceName: string;
    startsAt: string;
    endsAt?: string | null;
    lootMode?: string | null;
};

export type UpdateRaidRequest = {
    expectedVersion: number;
    title?: string | null;
    instanceName?: string | null;
    startsAt?: string | null;
    endsAt?: string | null;
    status?: string | null;
    lootMode?: string | null;
};

export type SaveSignupRequest = {
    characterId: string;
    status: 'ACCEPTED' | 'TENTATIVE' | 'DECLINED';
    note?: string | null;
};

export type SaveRosterRequest = {
    expectedVersion?: number | null;
    roster: Array<RosterSlot>;
    bench: Array<RosterSlot>;
};

export type SaveAssignmentRequest = {
    expectedVersion?: number | null;
    bossName: string;
    generalNotes?: string;
    tankTargetsByCharacterId?: {
        [key: string]: string;
    };
    healGroupsByCharacterId?: {
        [key: string]: string;
    };
    interruptOrderCharacterIds?: Array<string>;
    positionNotesByCharacterId?: {
        [key: string]: string;
    };
    personalNotesByCharacterId?: {
        [key: string]: string;
    };
};

export type TemplateRequest = {
    name: string;
    instanceName?: string;
    bossKey: string;
    bossName: string;
    generalNotes?: string;
    tankTargetLabels?: Array<string>;
    healGroupLabels?: Array<string>;
    interruptLabels?: Array<string>;
};

export type CreateLootAwardRequest = {
    characterId: string;
    itemId: number;
    itemName: string;
    itemLevel?: number | null;
    slot?: string | null;
    decisionType: string;
    priority?: string | null;
    note?: string | null;
};

export type VoidLootAwardRequest = {
    reason: string;
};

export type SessionExchangeResponse = {
    accessToken: string;
    expiresAt: string;
    player: PlayerProfile;
    permissions: Array<string>;
    authenticationProvider: 'DISCORD' | 'BOOTSTRAP';
};

export type MeResponse = {
    player: PlayerProfile;
    characters: Array<CharacterProfile>;
    permissions: Array<string>;
    authenticationProvider: string;
};

export type RaidDetailsResponse = {
    raid: Raid;
    signups: Array<Signup>;
    roster?: RosterDocument | null;
    assignments: Array<EncounterAssignment>;
    lootAwards: Array<LootAward>;
};

export type PublishResult = {
    raidId: string;
    publishVersion: number;
    queuedAssignmentDms: number;
};

export type HealthEnvelope = {
    data: Health;
};

export type FeatureFlagsEnvelope = {
    data: FeatureFlags;
};

export type SessionExchangeEnvelope = {
    data: SessionExchangeResponse;
};

export type MeEnvelope = {
    data: MeResponse;
};

export type TeamListEnvelope = {
    data: Array<Team>;
};

export type PlayerEnvelope = {
    data: PlayerProfile;
};

export type PlayerListEnvelope = {
    data: Array<PlayerProfile>;
};

export type CharacterEnvelope = {
    data: CharacterProfile;
};

export type CharacterListEnvelope = {
    data: Array<CharacterProfile>;
};

export type BisListEnvelope = {
    data: BisList;
};

export type RaidEnvelope = {
    data: Raid;
};

export type RaidListEnvelope = {
    data: Array<Raid>;
};

export type RaidDetailsEnvelope = {
    data: RaidDetailsResponse;
};

export type SignupEnvelope = {
    data: Signup;
};

export type SignupListEnvelope = {
    data: Array<Signup>;
};

export type RosterEnvelope = {
    data: RosterDocument;
};

export type AssignmentEnvelope = {
    data: EncounterAssignment;
};

export type AssignmentListEnvelope = {
    data: Array<EncounterAssignment>;
};

export type TemplateEnvelope = {
    data: EncounterTemplate;
};

export type TemplateListEnvelope = {
    data: Array<EncounterTemplate>;
};

export type LootAwardEnvelope = {
    data: LootAward;
};

export type LootAwardListEnvelope = {
    data: Array<LootAward>;
};

export type PublishResultEnvelope = {
    data: PublishResult;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Success
     */
    200: HealthEnvelope;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetFeaturesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/features';
};

export type GetFeaturesResponses = {
    /**
     * Success
     */
    200: FeatureFlagsEnvelope;
};

export type GetFeaturesResponse = GetFeaturesResponses[keyof GetFeaturesResponses];

export type GetSwaggerUiData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/docs';
};

export type GetSwaggerUiResponses = {
    /**
     * Swagger UI HTML
     */
    200: string;
};

export type GetSwaggerUiResponse = GetSwaggerUiResponses[keyof GetSwaggerUiResponses];

export type GetOpenApiYamlData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/openapi.yaml';
};

export type GetOpenApiYamlResponses = {
    /**
     * OpenAPI YAML
     */
    200: string;
};

export type GetOpenApiYamlResponse = GetOpenApiYamlResponses[keyof GetOpenApiYamlResponses];

export type StartDiscordLoginData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Exact allowlisted frontend callback URL.
         */
        returnUrl?: string;
    };
    url: '/auth/discord/start';
};

export type StartDiscordLoginErrors = {
    /**
     * Invalid request
     */
    400: ErrorEnvelope;
    /**
     * Feature is not configured
     */
    503: ErrorEnvelope;
};

export type StartDiscordLoginError = StartDiscordLoginErrors[keyof StartDiscordLoginErrors];

export type CompleteDiscordLoginData = {
    body?: never;
    path?: never;
    query?: {
        code?: string;
        state?: string;
        error?: string;
    };
    url: '/auth/discord/callback';
};

export type CompleteDiscordLoginErrors = {
    /**
     * Feature is not configured
     */
    503: ErrorEnvelope;
};

export type CompleteDiscordLoginError = CompleteDiscordLoginErrors[keyof CompleteDiscordLoginErrors];

export type ExchangeDiscordLoginCodeData = {
    body: ExchangeLoginCodeRequest;
    path?: never;
    query?: never;
    url: '/auth/session/exchange';
};

export type ExchangeDiscordLoginCodeErrors = {
    /**
     * Invalid request
     */
    400: ErrorEnvelope;
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
};

export type ExchangeDiscordLoginCodeError = ExchangeDiscordLoginCodeErrors[keyof ExchangeDiscordLoginCodeErrors];

export type ExchangeDiscordLoginCodeResponses = {
    /**
     * Success
     */
    200: SessionExchangeEnvelope;
};

export type ExchangeDiscordLoginCodeResponse = ExchangeDiscordLoginCodeResponses[keyof ExchangeDiscordLoginCodeResponses];

export type ExchangeBootstrapAdminTokenData = {
    body: ExchangeBootstrapAdminRequest;
    path?: never;
    query?: never;
    url: '/auth/admin/exchange';
};

export type ExchangeBootstrapAdminTokenErrors = {
    /**
     * Invalid request
     */
    400: ErrorEnvelope;
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
};

export type ExchangeBootstrapAdminTokenError = ExchangeBootstrapAdminTokenErrors[keyof ExchangeBootstrapAdminTokenErrors];

export type ExchangeBootstrapAdminTokenResponses = {
    /**
     * Success
     */
    200: SessionExchangeEnvelope;
};

export type ExchangeBootstrapAdminTokenResponse = ExchangeBootstrapAdminTokenResponses[keyof ExchangeBootstrapAdminTokenResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type LogoutErrors = {
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * Logged out
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me';
};

export type GetCurrentUserErrors = {
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
};

export type GetCurrentUserError = GetCurrentUserErrors[keyof GetCurrentUserErrors];

export type GetCurrentUserResponses = {
    /**
     * Success
     */
    200: MeEnvelope;
};

export type GetCurrentUserResponse = GetCurrentUserResponses[keyof GetCurrentUserResponses];

export type ListTeamsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/teams';
};

export type ListTeamsErrors = {
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
};

export type ListTeamsError = ListTeamsErrors[keyof ListTeamsErrors];

export type ListTeamsResponses = {
    /**
     * Success
     */
    200: TeamListEnvelope;
};

export type ListTeamsResponse = ListTeamsResponses[keyof ListTeamsResponses];

export type ListPlayersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/players';
};

export type ListPlayersErrors = {
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
};

export type ListPlayersError = ListPlayersErrors[keyof ListPlayersErrors];

export type ListPlayersResponses = {
    /**
     * Success
     */
    200: PlayerListEnvelope;
};

export type ListPlayersResponse = ListPlayersResponses[keyof ListPlayersResponses];

export type GetOwnPlayerData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/players/me';
};

export type GetOwnPlayerErrors = {
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
};

export type GetOwnPlayerError = GetOwnPlayerErrors[keyof GetOwnPlayerErrors];

export type GetOwnPlayerResponses = {
    /**
     * Success
     */
    200: MeEnvelope;
};

export type GetOwnPlayerResponse = GetOwnPlayerResponses[keyof GetOwnPlayerResponses];

export type UpdateOwnPlayerData = {
    body: UpdatePlayerRequest;
    path?: never;
    query?: never;
    url: '/players/me';
};

export type UpdateOwnPlayerErrors = {
    /**
     * Invalid request
     */
    400: ErrorEnvelope;
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
};

export type UpdateOwnPlayerError = UpdateOwnPlayerErrors[keyof UpdateOwnPlayerErrors];

export type UpdateOwnPlayerResponses = {
    /**
     * Success
     */
    200: PlayerEnvelope;
};

export type UpdateOwnPlayerResponse = UpdateOwnPlayerResponses[keyof UpdateOwnPlayerResponses];

export type ListOwnCharactersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/players/me/characters';
};

export type ListOwnCharactersErrors = {
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
};

export type ListOwnCharactersError = ListOwnCharactersErrors[keyof ListOwnCharactersErrors];

export type ListOwnCharactersResponses = {
    /**
     * Success
     */
    200: CharacterListEnvelope;
};

export type ListOwnCharactersResponse = ListOwnCharactersResponses[keyof ListOwnCharactersResponses];

export type CreateCharacterData = {
    body: CharacterRequest;
    path?: never;
    query?: never;
    url: '/players/me/characters';
};

export type CreateCharacterErrors = {
    /**
     * Invalid request
     */
    400: ErrorEnvelope;
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
    /**
     * Version conflict or disabled integration
     */
    409: ErrorEnvelope;
};

export type CreateCharacterError = CreateCharacterErrors[keyof CreateCharacterErrors];

export type CreateCharacterResponses = {
    /**
     * Created
     */
    201: CharacterEnvelope;
};

export type CreateCharacterResponse = CreateCharacterResponses[keyof CreateCharacterResponses];

export type GetPlayerData = {
    body?: never;
    path: {
        /**
         * Stable Jasmine Dragon internal user ID.
         */
        userId: string;
    };
    query?: never;
    url: '/players/{userId}';
};

export type GetPlayerErrors = {
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
};

export type GetPlayerError = GetPlayerErrors[keyof GetPlayerErrors];

export type GetPlayerResponses = {
    /**
     * Success
     */
    200: MeEnvelope;
};

export type GetPlayerResponse = GetPlayerResponses[keyof GetPlayerResponses];

export type UpdatePlayerData = {
    body: UpdatePlayerRequest;
    path: {
        /**
         * Stable Jasmine Dragon internal user ID.
         */
        userId: string;
    };
    query?: never;
    url: '/players/{userId}';
};

export type UpdatePlayerErrors = {
    /**
     * Invalid request
     */
    400: ErrorEnvelope;
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
};

export type UpdatePlayerError = UpdatePlayerErrors[keyof UpdatePlayerErrors];

export type UpdatePlayerResponses = {
    /**
     * Success
     */
    200: PlayerEnvelope;
};

export type UpdatePlayerResponse = UpdatePlayerResponses[keyof UpdatePlayerResponses];

export type GetPlayerLootHistoryData = {
    body?: never;
    path: {
        /**
         * Stable Jasmine Dragon internal user ID.
         */
        userId: string;
    };
    query?: never;
    url: '/players/{userId}/loot';
};

export type GetPlayerLootHistoryErrors = {
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
};

export type GetPlayerLootHistoryError = GetPlayerLootHistoryErrors[keyof GetPlayerLootHistoryErrors];

export type GetPlayerLootHistoryResponses = {
    /**
     * Success
     */
    200: LootAwardListEnvelope;
};

export type GetPlayerLootHistoryResponse = GetPlayerLootHistoryResponses[keyof GetPlayerLootHistoryResponses];

export type ListCharactersData = {
    body?: never;
    path?: never;
    query?: {
        verificationStatus?: 'PENDING' | 'VERIFIED' | 'REJECTED';
        teamId?: 'team-jasmine' | 'team-dragon';
    };
    url: '/characters';
};

export type ListCharactersErrors = {
    /**
     * Invalid request
     */
    400: ErrorEnvelope;
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
};

export type ListCharactersError = ListCharactersErrors[keyof ListCharactersErrors];

export type ListCharactersResponses = {
    /**
     * Success
     */
    200: CharacterListEnvelope;
};

export type ListCharactersResponse = ListCharactersResponses[keyof ListCharactersResponses];

export type GetCharacterData = {
    body?: never;
    path: {
        characterId: string;
    };
    query?: never;
    url: '/characters/{characterId}';
};

export type GetCharacterErrors = {
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
};

export type GetCharacterError = GetCharacterErrors[keyof GetCharacterErrors];

export type GetCharacterResponses = {
    /**
     * Success
     */
    200: CharacterEnvelope;
};

export type GetCharacterResponse = GetCharacterResponses[keyof GetCharacterResponses];

export type UpdateCharacterData = {
    body: CharacterRequest;
    path: {
        characterId: string;
    };
    query?: never;
    url: '/characters/{characterId}';
};

export type UpdateCharacterErrors = {
    /**
     * Invalid request
     */
    400: ErrorEnvelope;
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
};

export type UpdateCharacterError = UpdateCharacterErrors[keyof UpdateCharacterErrors];

export type UpdateCharacterResponses = {
    /**
     * Success
     */
    200: CharacterEnvelope;
};

export type UpdateCharacterResponse = UpdateCharacterResponses[keyof UpdateCharacterResponses];

export type VerifyCharacterData = {
    body: VerifyCharacterRequest;
    path: {
        characterId: string;
    };
    query?: never;
    url: '/characters/{characterId}/verify';
};

export type VerifyCharacterErrors = {
    /**
     * Invalid request
     */
    400: ErrorEnvelope;
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
};

export type VerifyCharacterError = VerifyCharacterErrors[keyof VerifyCharacterErrors];

export type VerifyCharacterResponses = {
    /**
     * Success
     */
    200: CharacterEnvelope;
};

export type VerifyCharacterResponse = VerifyCharacterResponses[keyof VerifyCharacterResponses];

export type GetBisListData = {
    body?: never;
    path: {
        characterId: string;
    };
    query?: never;
    url: '/characters/{characterId}/bis';
};

export type GetBisListErrors = {
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
};

export type GetBisListError = GetBisListErrors[keyof GetBisListErrors];

export type GetBisListResponses = {
    /**
     * Success
     */
    200: BisListEnvelope;
};

export type GetBisListResponse = GetBisListResponses[keyof GetBisListResponses];

export type SaveBisListData = {
    body: SaveBisListRequest;
    path: {
        characterId: string;
    };
    query?: never;
    url: '/characters/{characterId}/bis';
};

export type SaveBisListErrors = {
    /**
     * Invalid request
     */
    400: ErrorEnvelope;
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
    /**
     * Version conflict or disabled integration
     */
    409: ErrorEnvelope;
};

export type SaveBisListError = SaveBisListErrors[keyof SaveBisListErrors];

export type SaveBisListResponses = {
    /**
     * Success
     */
    200: BisListEnvelope;
};

export type SaveBisListResponse = SaveBisListResponses[keyof SaveBisListResponses];

export type GetCharacterLootHistoryData = {
    body?: never;
    path: {
        characterId: string;
    };
    query?: never;
    url: '/characters/{characterId}/loot';
};

export type GetCharacterLootHistoryErrors = {
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
};

export type GetCharacterLootHistoryError = GetCharacterLootHistoryErrors[keyof GetCharacterLootHistoryErrors];

export type GetCharacterLootHistoryResponses = {
    /**
     * Success
     */
    200: LootAwardListEnvelope;
};

export type GetCharacterLootHistoryResponse = GetCharacterLootHistoryResponses[keyof GetCharacterLootHistoryResponses];

export type ListRaidsData = {
    body?: never;
    path?: never;
    query?: {
        teamId?: 'team-jasmine' | 'team-dragon';
    };
    url: '/raids';
};

export type ListRaidsErrors = {
    /**
     * Invalid request
     */
    400: ErrorEnvelope;
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
};

export type ListRaidsError = ListRaidsErrors[keyof ListRaidsErrors];

export type ListRaidsResponses = {
    /**
     * Success
     */
    200: RaidListEnvelope;
};

export type ListRaidsResponse = ListRaidsResponses[keyof ListRaidsResponses];

export type CreateRaidData = {
    body: CreateRaidRequest;
    path?: never;
    query?: never;
    url: '/raids';
};

export type CreateRaidErrors = {
    /**
     * Invalid request
     */
    400: ErrorEnvelope;
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
    /**
     * Version conflict or disabled integration
     */
    409: ErrorEnvelope;
};

export type CreateRaidError = CreateRaidErrors[keyof CreateRaidErrors];

export type CreateRaidResponses = {
    /**
     * Created
     */
    201: RaidEnvelope;
};

export type CreateRaidResponse = CreateRaidResponses[keyof CreateRaidResponses];

export type GetRaidData = {
    body?: never;
    path: {
        raidId: string;
    };
    query?: never;
    url: '/raids/{raidId}';
};

export type GetRaidErrors = {
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
};

export type GetRaidError = GetRaidErrors[keyof GetRaidErrors];

export type GetRaidResponses = {
    /**
     * Success
     */
    200: RaidDetailsEnvelope;
};

export type GetRaidResponse = GetRaidResponses[keyof GetRaidResponses];

export type UpdateRaidData = {
    body: UpdateRaidRequest;
    path: {
        raidId: string;
    };
    query?: never;
    url: '/raids/{raidId}';
};

export type UpdateRaidErrors = {
    /**
     * Invalid request
     */
    400: ErrorEnvelope;
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
    /**
     * Version conflict or disabled integration
     */
    409: ErrorEnvelope;
};

export type UpdateRaidError = UpdateRaidErrors[keyof UpdateRaidErrors];

export type UpdateRaidResponses = {
    /**
     * Success
     */
    200: RaidEnvelope;
};

export type UpdateRaidResponse = UpdateRaidResponses[keyof UpdateRaidResponses];

export type SaveSignupData = {
    body: SaveSignupRequest;
    path: {
        raidId: string;
    };
    query?: never;
    url: '/raids/{raidId}/signup';
};

export type SaveSignupErrors = {
    /**
     * Invalid request
     */
    400: ErrorEnvelope;
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
};

export type SaveSignupError = SaveSignupErrors[keyof SaveSignupErrors];

export type SaveSignupResponses = {
    /**
     * Success
     */
    200: SignupEnvelope;
};

export type SaveSignupResponse = SaveSignupResponses[keyof SaveSignupResponses];

export type ListRaidSignupsData = {
    body?: never;
    path: {
        raidId: string;
    };
    query?: never;
    url: '/raids/{raidId}/signups';
};

export type ListRaidSignupsErrors = {
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
};

export type ListRaidSignupsError = ListRaidSignupsErrors[keyof ListRaidSignupsErrors];

export type ListRaidSignupsResponses = {
    /**
     * Success
     */
    200: SignupListEnvelope;
};

export type ListRaidSignupsResponse = ListRaidSignupsResponses[keyof ListRaidSignupsResponses];

export type GetRosterData = {
    body?: never;
    path: {
        raidId: string;
    };
    query?: never;
    url: '/raids/{raidId}/roster';
};

export type GetRosterErrors = {
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
};

export type GetRosterError = GetRosterErrors[keyof GetRosterErrors];

export type GetRosterResponses = {
    /**
     * Success
     */
    200: RosterEnvelope;
};

export type GetRosterResponse = GetRosterResponses[keyof GetRosterResponses];

export type SaveRosterData = {
    body: SaveRosterRequest;
    path: {
        raidId: string;
    };
    query?: never;
    url: '/raids/{raidId}/roster';
};

export type SaveRosterErrors = {
    /**
     * Invalid request
     */
    400: ErrorEnvelope;
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
    /**
     * Version conflict or disabled integration
     */
    409: ErrorEnvelope;
};

export type SaveRosterError = SaveRosterErrors[keyof SaveRosterErrors];

export type SaveRosterResponses = {
    /**
     * Success
     */
    200: RosterEnvelope;
};

export type SaveRosterResponse = SaveRosterResponses[keyof SaveRosterResponses];

export type ListAssignmentsData = {
    body?: never;
    path: {
        raidId: string;
    };
    query?: never;
    url: '/raids/{raidId}/assignments';
};

export type ListAssignmentsErrors = {
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
};

export type ListAssignmentsError = ListAssignmentsErrors[keyof ListAssignmentsErrors];

export type ListAssignmentsResponses = {
    /**
     * Success
     */
    200: AssignmentListEnvelope;
};

export type ListAssignmentsResponse = ListAssignmentsResponses[keyof ListAssignmentsResponses];

export type SaveAssignmentData = {
    body: SaveAssignmentRequest;
    path: {
        raidId: string;
        bossKey: string;
    };
    query?: never;
    url: '/raids/{raidId}/assignments/{bossKey}';
};

export type SaveAssignmentErrors = {
    /**
     * Invalid request
     */
    400: ErrorEnvelope;
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
    /**
     * Version conflict or disabled integration
     */
    409: ErrorEnvelope;
};

export type SaveAssignmentError = SaveAssignmentErrors[keyof SaveAssignmentErrors];

export type SaveAssignmentResponses = {
    /**
     * Success
     */
    200: AssignmentEnvelope;
};

export type SaveAssignmentResponse = SaveAssignmentResponses[keyof SaveAssignmentResponses];

export type PublishRaidToDiscordData = {
    body?: never;
    path: {
        raidId: string;
    };
    query?: never;
    url: '/raids/{raidId}/publish';
};

export type PublishRaidToDiscordErrors = {
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
    /**
     * Version conflict or disabled integration
     */
    409: ErrorEnvelope;
};

export type PublishRaidToDiscordError = PublishRaidToDiscordErrors[keyof PublishRaidToDiscordErrors];

export type PublishRaidToDiscordResponses = {
    /**
     * Queued
     */
    202: PublishResultEnvelope;
};

export type PublishRaidToDiscordResponse = PublishRaidToDiscordResponses[keyof PublishRaidToDiscordResponses];

export type ListRaidLootAwardsData = {
    body?: never;
    path: {
        raidId: string;
    };
    query?: never;
    url: '/raids/{raidId}/loot-awards';
};

export type ListRaidLootAwardsErrors = {
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
};

export type ListRaidLootAwardsError = ListRaidLootAwardsErrors[keyof ListRaidLootAwardsErrors];

export type ListRaidLootAwardsResponses = {
    /**
     * Success
     */
    200: LootAwardListEnvelope;
};

export type ListRaidLootAwardsResponse = ListRaidLootAwardsResponses[keyof ListRaidLootAwardsResponses];

export type CreateLootAwardData = {
    body: CreateLootAwardRequest;
    path: {
        raidId: string;
    };
    query?: never;
    url: '/raids/{raidId}/loot-awards';
};

export type CreateLootAwardErrors = {
    /**
     * Invalid request
     */
    400: ErrorEnvelope;
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
    /**
     * Version conflict or disabled integration
     */
    409: ErrorEnvelope;
};

export type CreateLootAwardError = CreateLootAwardErrors[keyof CreateLootAwardErrors];

export type CreateLootAwardResponses = {
    /**
     * Created
     */
    201: LootAwardEnvelope;
};

export type CreateLootAwardResponse = CreateLootAwardResponses[keyof CreateLootAwardResponses];

export type VoidLootAwardData = {
    body: VoidLootAwardRequest;
    path: {
        raidId: string;
        awardId: string;
    };
    query?: never;
    url: '/raids/{raidId}/loot-awards/{awardId}/void';
};

export type VoidLootAwardErrors = {
    /**
     * Invalid request
     */
    400: ErrorEnvelope;
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
};

export type VoidLootAwardError = VoidLootAwardErrors[keyof VoidLootAwardErrors];

export type VoidLootAwardResponses = {
    /**
     * Success
     */
    200: LootAwardEnvelope;
};

export type VoidLootAwardResponse = VoidLootAwardResponses[keyof VoidLootAwardResponses];

export type ListEncounterTemplatesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/templates';
};

export type ListEncounterTemplatesErrors = {
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
};

export type ListEncounterTemplatesError = ListEncounterTemplatesErrors[keyof ListEncounterTemplatesErrors];

export type ListEncounterTemplatesResponses = {
    /**
     * Success
     */
    200: TemplateListEnvelope;
};

export type ListEncounterTemplatesResponse = ListEncounterTemplatesResponses[keyof ListEncounterTemplatesResponses];

export type CreateEncounterTemplateData = {
    body: TemplateRequest;
    path?: never;
    query?: never;
    url: '/templates';
};

export type CreateEncounterTemplateErrors = {
    /**
     * Invalid request
     */
    400: ErrorEnvelope;
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
    /**
     * Version conflict or disabled integration
     */
    409: ErrorEnvelope;
};

export type CreateEncounterTemplateError = CreateEncounterTemplateErrors[keyof CreateEncounterTemplateErrors];

export type CreateEncounterTemplateResponses = {
    /**
     * Created
     */
    201: TemplateEnvelope;
};

export type CreateEncounterTemplateResponse = CreateEncounterTemplateResponses[keyof CreateEncounterTemplateResponses];

export type DeleteEncounterTemplateData = {
    body?: never;
    path: {
        templateId: string;
    };
    query?: never;
    url: '/templates/{templateId}';
};

export type DeleteEncounterTemplateErrors = {
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
};

export type DeleteEncounterTemplateError = DeleteEncounterTemplateErrors[keyof DeleteEncounterTemplateErrors];

export type DeleteEncounterTemplateResponses = {
    /**
     * Deleted
     */
    204: void;
};

export type DeleteEncounterTemplateResponse = DeleteEncounterTemplateResponses[keyof DeleteEncounterTemplateResponses];

export type GetEncounterTemplateData = {
    body?: never;
    path: {
        templateId: string;
    };
    query?: never;
    url: '/templates/{templateId}';
};

export type GetEncounterTemplateErrors = {
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
};

export type GetEncounterTemplateError = GetEncounterTemplateErrors[keyof GetEncounterTemplateErrors];

export type GetEncounterTemplateResponses = {
    /**
     * Success
     */
    200: TemplateEnvelope;
};

export type GetEncounterTemplateResponse = GetEncounterTemplateResponses[keyof GetEncounterTemplateResponses];

export type UpdateEncounterTemplateData = {
    body: TemplateRequest;
    path: {
        templateId: string;
    };
    query?: never;
    url: '/templates/{templateId}';
};

export type UpdateEncounterTemplateErrors = {
    /**
     * Invalid request
     */
    400: ErrorEnvelope;
    /**
     * Authentication required or session expired
     */
    401: ErrorEnvelope;
    /**
     * Insufficient permission
     */
    403: ErrorEnvelope;
    /**
     * Record or feature not found
     */
    404: ErrorEnvelope;
};

export type UpdateEncounterTemplateError = UpdateEncounterTemplateErrors[keyof UpdateEncounterTemplateErrors];

export type UpdateEncounterTemplateResponses = {
    /**
     * Success
     */
    200: TemplateEnvelope;
};

export type UpdateEncounterTemplateResponse = UpdateEncounterTemplateResponses[keyof UpdateEncounterTemplateResponses];
