// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zApiError = z.object({
    code: z.string(),
    message: z.string(),
    details: z.unknown().optional()
});

export const zErrorEnvelope = z.object({
    error: zApiError
});

export const zHealth = z.object({
    service: z.string(),
    status: z.string(),
    utc: z.iso.datetime()
});

export const zFeatureFlags = z.object({
    discordOAuth: z.boolean(),
    bootstrapAdminLogin: z.boolean(),
    discordPublishing: z.boolean(),
    discordDirectMessages: z.boolean(),
    discordReminders: z.boolean()
});

export const zTeam = z.object({
    teamId: z.string(),
    name: z.string(),
    isMainRoster: z.boolean(),
    defaultLootMode: z.enum(['LOOT_COUNCIL', 'NONE'])
});

export const zPlayerProfile = z.object({
    userId: z.string(),
    discordUserId: z.string().nullish(),
    discordUsername: z.string().nullish(),
    displayName: z.string(),
    avatarHash: z.string().nullish(),
    isOfficer: z.boolean(),
    teamIds: z.array(z.string()),
    timeZone: z.string(),
    authenticationProviders: z.array(z.enum(['DISCORD', 'BOOTSTRAP'])),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime()
});

export const zCharacterProfile = z.object({
    characterId: z.string(),
    userId: z.string(),
    discordUserId: z.string().nullish(),
    name: z.string(),
    realm: z.string(),
    region: z.string(),
    characterClass: z.string(),
    primarySpec: z.string(),
    eligibleRoles: z.array(z.enum([
        'TANK',
        'HEALER',
        'DPS'
    ])),
    teamIds: z.array(z.string()),
    isMain: z.boolean(),
    verificationStatus: z.enum([
        'PENDING',
        'VERIFIED',
        'REJECTED'
    ]),
    verificationMethod: z.string(),
    verifiedByUserId: z.string().nullish(),
    verifiedAt: z.iso.datetime().nullish(),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime()
});

export const zBisItem = z.object({
    itemId: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    itemName: z.string(),
    slot: z.string(),
    priority: z.int(),
    source: z.string().nullish(),
    note: z.string().nullish()
});

export const zBisList = z.object({
    characterId: z.string(),
    version: z.int(),
    phaseOrTier: z.string().nullish(),
    items: z.array(zBisItem),
    updatedAt: z.iso.datetime()
});

export const zRaid = z.object({
    raidId: z.string(),
    teamId: z.string(),
    title: z.string(),
    instanceName: z.string(),
    startsAt: z.iso.datetime(),
    endsAt: z.iso.datetime().nullish(),
    status: z.enum([
        'DRAFT',
        'PUBLISHED',
        'CANCELLED',
        'COMPLETED'
    ]),
    lootMode: z.string(),
    discordMessageId: z.string().nullish(),
    publishVersion: z.int(),
    version: z.int(),
    createdByUserId: z.string(),
    createdAt: z.iso.datetime(),
    updatedAt: z.iso.datetime()
});

export const zSignup = z.object({
    raidId: z.string(),
    userId: z.string(),
    discordUserId: z.string().nullish(),
    characterId: z.string(),
    status: z.enum([
        'ACCEPTED',
        'TENTATIVE',
        'DECLINED'
    ]),
    note: z.string().nullish(),
    updatedAt: z.iso.datetime()
});

export const zRosterSlot = z.object({
    characterId: z.string(),
    role: z.string(),
    group: z.int(),
    position: z.int(),
    note: z.string().nullish()
});

export const zRosterDocument = z.object({
    raidId: z.string(),
    version: z.int(),
    roster: z.array(zRosterSlot),
    bench: z.array(zRosterSlot),
    updatedAt: z.iso.datetime(),
    updatedByUserId: z.string()
});

export const zEncounterAssignment = z.object({
    raidId: z.string(),
    bossKey: z.string(),
    bossName: z.string(),
    version: z.int(),
    generalNotes: z.string(),
    tankTargetsByCharacterId: z.record(z.string(), z.string()),
    healGroupsByCharacterId: z.record(z.string(), z.string()),
    interruptOrderCharacterIds: z.array(z.string()),
    positionNotesByCharacterId: z.record(z.string(), z.string()),
    personalNotesByCharacterId: z.record(z.string(), z.string()),
    updatedAt: z.iso.datetime(),
    updatedByUserId: z.string()
});

export const zEncounterTemplate = z.object({
    templateId: z.string(),
    name: z.string(),
    instanceName: z.string(),
    bossKey: z.string(),
    bossName: z.string(),
    generalNotes: z.string(),
    tankTargetLabels: z.array(z.string()),
    healGroupLabels: z.array(z.string()),
    interruptLabels: z.array(z.string()),
    updatedAt: z.iso.datetime()
});

export const zLootAward = z.object({
    awardId: z.string(),
    raidId: z.string(),
    teamId: z.string(),
    characterId: z.string(),
    userId: z.string(),
    discordUserId: z.string().nullish(),
    itemId: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    itemName: z.string(),
    itemLevel: z.int().nullish(),
    slot: z.string().nullish(),
    decisionType: z.string(),
    priority: z.string().nullish(),
    note: z.string().nullish(),
    lootSystem: z.string(),
    awardedByUserId: z.string(),
    awardedAt: z.iso.datetime(),
    status: z.enum(['ACTIVE', 'VOIDED']),
    voidReason: z.string().nullish(),
    voidedByUserId: z.string().nullish(),
    voidedAt: z.iso.datetime().nullish(),
    bisStatusAtAward: z.string().nullish(),
    bisPriorityAtAward: z.int().nullish()
});

export const zExchangeLoginCodeRequest = z.object({
    code: z.string()
});

export const zExchangeBootstrapAdminRequest = z.object({
    token: z.string()
});

export const zUpdatePlayerRequest = z.object({
    displayName: z.string().optional(),
    teamIds: z.array(z.string()).optional(),
    timeZone: z.string().optional()
});

export const zCharacterRequest = z.object({
    name: z.string(),
    realm: z.string(),
    region: z.string().default('EU'),
    characterClass: z.string(),
    primarySpec: z.string(),
    eligibleRoles: z.array(z.string()),
    teamIds: z.array(z.string()),
    isMain: z.boolean()
});

export const zVerifyCharacterRequest = z.object({
    approved: z.boolean().optional().default(true),
    note: z.string().nullish()
});

export const zSaveBisListRequest = z.object({
    expectedVersion: z.int().nullish(),
    phaseOrTier: z.string().nullish(),
    items: z.array(zBisItem)
});

export const zCreateRaidRequest = z.object({
    teamId: z.string(),
    title: z.string(),
    instanceName: z.string(),
    startsAt: z.iso.datetime(),
    endsAt: z.iso.datetime().nullish(),
    lootMode: z.string().nullish()
});

export const zUpdateRaidRequest = z.object({
    expectedVersion: z.int(),
    title: z.string().nullish(),
    instanceName: z.string().nullish(),
    startsAt: z.iso.datetime().nullish(),
    endsAt: z.iso.datetime().nullish(),
    status: z.string().nullish(),
    lootMode: z.string().nullish()
});

export const zSaveSignupRequest = z.object({
    characterId: z.string(),
    status: z.enum([
        'ACCEPTED',
        'TENTATIVE',
        'DECLINED'
    ]),
    note: z.string().nullish()
});

export const zSaveRosterRequest = z.object({
    expectedVersion: z.int().nullish(),
    roster: z.array(zRosterSlot),
    bench: z.array(zRosterSlot)
});

export const zSaveAssignmentRequest = z.object({
    expectedVersion: z.int().nullish(),
    bossName: z.string(),
    generalNotes: z.string().optional(),
    tankTargetsByCharacterId: z.record(z.string(), z.string()).optional(),
    healGroupsByCharacterId: z.record(z.string(), z.string()).optional(),
    interruptOrderCharacterIds: z.array(z.string()).optional(),
    positionNotesByCharacterId: z.record(z.string(), z.string()).optional(),
    personalNotesByCharacterId: z.record(z.string(), z.string()).optional()
});

export const zTemplateRequest = z.object({
    name: z.string(),
    instanceName: z.string().optional(),
    bossKey: z.string(),
    bossName: z.string(),
    generalNotes: z.string().optional(),
    tankTargetLabels: z.array(z.string()).optional(),
    healGroupLabels: z.array(z.string()).optional(),
    interruptLabels: z.array(z.string()).optional()
});

export const zCreateLootAwardRequest = z.object({
    characterId: z.string(),
    itemId: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    itemName: z.string(),
    itemLevel: z.int().nullish(),
    slot: z.string().nullish(),
    decisionType: z.string(),
    priority: z.string().nullish(),
    note: z.string().nullish()
});

export const zVoidLootAwardRequest = z.object({
    reason: z.string()
});

export const zSessionExchangeResponse = z.object({
    accessToken: z.string(),
    expiresAt: z.iso.datetime(),
    player: zPlayerProfile,
    permissions: z.array(z.string()),
    authenticationProvider: z.enum(['DISCORD', 'BOOTSTRAP'])
});

export const zMeResponse = z.object({
    player: zPlayerProfile,
    characters: z.array(zCharacterProfile),
    permissions: z.array(z.string()),
    authenticationProvider: z.string()
});

export const zRaidDetailsResponse = z.object({
    raid: zRaid,
    signups: z.array(zSignup),
    roster: zRosterDocument.nullish(),
    assignments: z.array(zEncounterAssignment),
    lootAwards: z.array(zLootAward)
});

export const zPublishResult = z.object({
    raidId: z.string(),
    publishVersion: z.int(),
    queuedAssignmentDms: z.int()
});

export const zHealthEnvelope = z.object({
    data: zHealth
});

export const zFeatureFlagsEnvelope = z.object({
    data: zFeatureFlags
});

export const zSessionExchangeEnvelope = z.object({
    data: zSessionExchangeResponse
});

export const zMeEnvelope = z.object({
    data: zMeResponse
});

export const zTeamListEnvelope = z.object({
    data: z.array(zTeam)
});

export const zPlayerEnvelope = z.object({
    data: zPlayerProfile
});

export const zPlayerListEnvelope = z.object({
    data: z.array(zPlayerProfile)
});

export const zCharacterEnvelope = z.object({
    data: zCharacterProfile
});

export const zCharacterListEnvelope = z.object({
    data: z.array(zCharacterProfile)
});

export const zBisListEnvelope = z.object({
    data: zBisList
});

export const zRaidEnvelope = z.object({
    data: zRaid
});

export const zRaidListEnvelope = z.object({
    data: z.array(zRaid)
});

export const zRaidDetailsEnvelope = z.object({
    data: zRaidDetailsResponse
});

export const zSignupEnvelope = z.object({
    data: zSignup
});

export const zSignupListEnvelope = z.object({
    data: z.array(zSignup)
});

export const zRosterEnvelope = z.object({
    data: zRosterDocument
});

export const zAssignmentEnvelope = z.object({
    data: zEncounterAssignment
});

export const zAssignmentListEnvelope = z.object({
    data: z.array(zEncounterAssignment)
});

export const zTemplateEnvelope = z.object({
    data: zEncounterTemplate
});

export const zTemplateListEnvelope = z.object({
    data: z.array(zEncounterTemplate)
});

export const zLootAwardEnvelope = z.object({
    data: zLootAward
});

export const zLootAwardListEnvelope = z.object({
    data: z.array(zLootAward)
});

export const zPublishResultEnvelope = z.object({
    data: zPublishResult
});

/**
 * Success
 */
export const zGetHealthResponse = zHealthEnvelope;

/**
 * Success
 */
export const zGetFeaturesResponse = zFeatureFlagsEnvelope;

/**
 * Swagger UI HTML
 */
export const zGetSwaggerUiResponse = z.string();

/**
 * OpenAPI YAML
 */
export const zGetOpenApiYamlResponse = z.string();

export const zStartDiscordLoginQuery = z.object({
    returnUrl: z.url().optional()
});

export const zCompleteDiscordLoginQuery = z.object({
    code: z.string().optional(),
    state: z.string().optional(),
    error: z.string().optional()
});

export const zExchangeDiscordLoginCodeBody = zExchangeLoginCodeRequest;

/**
 * Success
 */
export const zExchangeDiscordLoginCodeResponse = zSessionExchangeEnvelope;

export const zExchangeBootstrapAdminTokenBody = zExchangeBootstrapAdminRequest;

/**
 * Success
 */
export const zExchangeBootstrapAdminTokenResponse = zSessionExchangeEnvelope;

/**
 * Logged out
 */
export const zLogoutResponse = z.void();

/**
 * Success
 */
export const zGetCurrentUserResponse = zMeEnvelope;

/**
 * Success
 */
export const zListTeamsResponse = zTeamListEnvelope;

/**
 * Success
 */
export const zListPlayersResponse = zPlayerListEnvelope;

/**
 * Success
 */
export const zGetOwnPlayerResponse = zMeEnvelope;

export const zUpdateOwnPlayerBody = zUpdatePlayerRequest;

/**
 * Success
 */
export const zUpdateOwnPlayerResponse = zPlayerEnvelope;

/**
 * Success
 */
export const zListOwnCharactersResponse = zCharacterListEnvelope;

export const zCreateCharacterBody = zCharacterRequest;

/**
 * Created
 */
export const zCreateCharacterResponse = zCharacterEnvelope;

export const zGetPlayerPath = z.object({
    userId: z.string()
});

/**
 * Success
 */
export const zGetPlayerResponse = zMeEnvelope;

export const zUpdatePlayerBody = zUpdatePlayerRequest;

export const zUpdatePlayerPath = z.object({
    userId: z.string()
});

/**
 * Success
 */
export const zUpdatePlayerResponse = zPlayerEnvelope;

export const zGetPlayerLootHistoryPath = z.object({
    userId: z.string()
});

/**
 * Success
 */
export const zGetPlayerLootHistoryResponse = zLootAwardListEnvelope;

export const zListCharactersQuery = z.object({
    verificationStatus: z.enum([
        'PENDING',
        'VERIFIED',
        'REJECTED'
    ]).optional(),
    teamId: z.enum(['team-jasmine', 'team-dragon']).optional()
});

/**
 * Success
 */
export const zListCharactersResponse = zCharacterListEnvelope;

export const zGetCharacterPath = z.object({
    characterId: z.string()
});

/**
 * Success
 */
export const zGetCharacterResponse = zCharacterEnvelope;

export const zUpdateCharacterBody = zCharacterRequest;

export const zUpdateCharacterPath = z.object({
    characterId: z.string()
});

/**
 * Success
 */
export const zUpdateCharacterResponse = zCharacterEnvelope;

export const zVerifyCharacterBody = zVerifyCharacterRequest;

export const zVerifyCharacterPath = z.object({
    characterId: z.string()
});

/**
 * Success
 */
export const zVerifyCharacterResponse = zCharacterEnvelope;

export const zGetBisListPath = z.object({
    characterId: z.string()
});

/**
 * Success
 */
export const zGetBisListResponse = zBisListEnvelope;

export const zSaveBisListBody = zSaveBisListRequest;

export const zSaveBisListPath = z.object({
    characterId: z.string()
});

/**
 * Success
 */
export const zSaveBisListResponse = zBisListEnvelope;

export const zGetCharacterLootHistoryPath = z.object({
    characterId: z.string()
});

/**
 * Success
 */
export const zGetCharacterLootHistoryResponse = zLootAwardListEnvelope;

export const zListRaidsQuery = z.object({
    teamId: z.enum(['team-jasmine', 'team-dragon']).optional().default('team-jasmine')
});

/**
 * Success
 */
export const zListRaidsResponse = zRaidListEnvelope;

export const zCreateRaidBody = zCreateRaidRequest;

/**
 * Created
 */
export const zCreateRaidResponse = zRaidEnvelope;

export const zGetRaidPath = z.object({
    raidId: z.string()
});

/**
 * Success
 */
export const zGetRaidResponse = zRaidDetailsEnvelope;

export const zUpdateRaidBody = zUpdateRaidRequest;

export const zUpdateRaidPath = z.object({
    raidId: z.string()
});

/**
 * Success
 */
export const zUpdateRaidResponse = zRaidEnvelope;

export const zSaveSignupBody = zSaveSignupRequest;

export const zSaveSignupPath = z.object({
    raidId: z.string()
});

/**
 * Success
 */
export const zSaveSignupResponse = zSignupEnvelope;

export const zListRaidSignupsPath = z.object({
    raidId: z.string()
});

/**
 * Success
 */
export const zListRaidSignupsResponse = zSignupListEnvelope;

export const zGetRosterPath = z.object({
    raidId: z.string()
});

/**
 * Success
 */
export const zGetRosterResponse = zRosterEnvelope;

export const zSaveRosterBody = zSaveRosterRequest;

export const zSaveRosterPath = z.object({
    raidId: z.string()
});

/**
 * Success
 */
export const zSaveRosterResponse = zRosterEnvelope;

export const zListAssignmentsPath = z.object({
    raidId: z.string()
});

/**
 * Success
 */
export const zListAssignmentsResponse = zAssignmentListEnvelope;

export const zSaveAssignmentBody = zSaveAssignmentRequest;

export const zSaveAssignmentPath = z.object({
    raidId: z.string(),
    bossKey: z.string()
});

/**
 * Success
 */
export const zSaveAssignmentResponse = zAssignmentEnvelope;

export const zPublishRaidToDiscordPath = z.object({
    raidId: z.string()
});

/**
 * Queued
 */
export const zPublishRaidToDiscordResponse = zPublishResultEnvelope;

export const zListRaidLootAwardsPath = z.object({
    raidId: z.string()
});

/**
 * Success
 */
export const zListRaidLootAwardsResponse = zLootAwardListEnvelope;

export const zCreateLootAwardBody = zCreateLootAwardRequest;

export const zCreateLootAwardPath = z.object({
    raidId: z.string()
});

/**
 * Created
 */
export const zCreateLootAwardResponse = zLootAwardEnvelope;

export const zVoidLootAwardBody = zVoidLootAwardRequest;

export const zVoidLootAwardPath = z.object({
    raidId: z.string(),
    awardId: z.string()
});

/**
 * Success
 */
export const zVoidLootAwardResponse = zLootAwardEnvelope;

/**
 * Success
 */
export const zListEncounterTemplatesResponse = zTemplateListEnvelope;

export const zCreateEncounterTemplateBody = zTemplateRequest;

/**
 * Created
 */
export const zCreateEncounterTemplateResponse = zTemplateEnvelope;

export const zDeleteEncounterTemplatePath = z.object({
    templateId: z.string()
});

/**
 * Deleted
 */
export const zDeleteEncounterTemplateResponse = z.void();

export const zGetEncounterTemplatePath = z.object({
    templateId: z.string()
});

/**
 * Success
 */
export const zGetEncounterTemplateResponse = zTemplateEnvelope;

export const zUpdateEncounterTemplateBody = zTemplateRequest;

export const zUpdateEncounterTemplatePath = z.object({
    templateId: z.string()
});

/**
 * Success
 */
export const zUpdateEncounterTemplateResponse = zTemplateEnvelope;
